version: '3.8'

services:
  openhab:
    image: openhab/openhab
    container_name: openhab
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - "./openhab_addons:/openhab/addons"
      - "./openhab_conf:/openhab/conf"
      - "./openhab_userdata:/openhab/userdata"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Moscow"
      LC_ALL: ru_RU.UTF-8
      LANG: ru_RU.UTF-8
      LANGUAGE: ru_RU.UTF-8
